send original message to main channel  if alleged spam was unbanned b…
umputun/tg-spam pull request #173
Opened 2024-11-07 21:02 UTC by evgeny-boger

…y admin

2024-11-25 13:13 UTC, MissiaL commented
@umputun could you check this PR?
It's really helpful PR

2024-12-03 09:45 UTC, MissiaL commented
We often have cases where a user is banned by accident. Group administrators have to search for this message and restore it, forward this message manually. This takes a lot of time in the flow of a large amount of spam.
In this PR, the user name is indicated when the message is restored, which is also very convenient

2024-12-03 17:32 UTC, umputun commented
> We often have cases where a user is banned by accident. Group administrators have to search for this message and restore it, forward this message manually. This takes a lot of time in the flow of a large amount of spam. In this PR, the user name is indicated when the message is restored, which is also very convenient

I see, makes sense to me now.

2024-12-03 17:45 UTC, umputun requested changes
Thanks. Generally, the change looks legitimate to me. I didn't like the nested logic with if/else/if/else and asked to simplify it.

Another issue is that it has no tests for the change; it would be nice to have them added.

2024-12-03 17:45 UTC, umputun commented on app/events/admin.go
> +		} else {
the logic with nested if/else is hard to read and follow. Can you simplify it by making it a single-level and preferable without else.

2024-12-04 06:37 UTC, paskal requested changes

2024-12-04 06:37 UTC, paskal commented on README.md
> +- `--message.restore=, [$MESSAGE_RESTORE]` - message sent to the group when original message is unbanned by admin, can be empty to supress reporting the original message
We should better highlight that the bot would be the poster of that message, and not the original message forwarded or magically restored.

2024-12-04 06:37 UTC, paskal commented on README.md
> +      --message.restore=            restore message [$MESSAGE_RESTORE]
This description is insufficient.

2024-12-04 06:37 UTC, paskal commented on app/events/listener.go
> +	RestoreMsg			    string        // message to send on restore
nit: for tabs creeped in otherwise space-formatted file here

2024-12-04 06:37 UTC, paskal commented on app/main.go
> +		Restore string `long:"restore" env:"RESTORE" default:"" description:"restore message"`
Same as in the Readme, should be updated to describe better what setting this variable does.

2025-03-06 00:45 UTC, umputun commented
seems abandoned. feel free to reopen if you want to complete it some day

2025-03-06 00:45 UTC, closed without merging